### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/cocoapods-stats#1]

**Comment by segiddins** [comment]
Rainforest literally will not let me release until there are tests :)

**Comment by orta** [comment]
`rake specs` works now, there's just not any tests yet

**Comment by segiddins** [comment]
It needs to be `rake spec`

**Comment by orta** [comment]
https://github.com/CocoaPods/cocoapods-stats/commit/0d31ee834cc4bde5c3071b2cc86a1a997d4f7a49

;)
