### ISSUE TITLE
Differentiate between pod try, and normal pod installs

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods-stats#11]
My initial thoughts were that this could come through an ENV var, but really anything that allows communication between the two plugins.

**Comment by segiddins** [comment]
Think I got this in https://github.com/CocoaPods/cocoapods-stats/commit/9b0cfd7b462dd738728c63d0d4b9f5a686a8505e#diff-a916cbeb849aa9ef50da87f2441db859R41.
