### ISSUE TITLE
Long timeout when stats server is not accessible

### ISSUE THREAD

**Issue by Ashton-W** [CocoaPods/cocoapods-stats#22]
In certain strict security environments the networking is such that the stats plugin can't even access the internet, unfortunately right now it 'hangs' while waiting for a timeout (I'm sure the corporate proxy is more to blame here for not following HTTP).

---

From [CocoaPods/issues/4032](https://github.com/CocoaPods/CocoaPods/issues/4032)

**Comment by segiddins** [comment]
The hanging has been fixed by sending stats asynchronously and out of process on master already.

**Comment by Ashton-W** [comment]
Oh, cool
