### ISSUE TITLE
Define COCOAPODS_DISABLE_STATS equivalent in Podfile

### ISSUE THREAD

**Issue by Pe-te** [CocoaPods/cocoapods-stats#23]
Is there a way to define the COCOAPODS_DISABLE_STATS variable in the Podfile? We don't want to change the enviroment variables on every developer machine.

**Comment by segiddins** [comment]
You can do `ENV["COCOAPODS_DISABLE_STATS"] = "1"`

**Comment by Pe-te** [comment]
nice, thank you!
