### ISSUE TITLE
If cocoapods-stats is triggered for a machine before `pod setup` is ran and there is no master repo it crashes.

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/cocoapods-stats#28]
Whilst fixing this https://github.com/jcampbell05/cocoapods-deploy/issues/3

I discovered that `cocoapods-stats` will crash if CocoaPods hasn't had `pod setup` ran. As a workaround in my plugin I set the environmental variable to disable `cocoapods-stats` unfortunately losing the statistics for CI builds (I will get around to fixing this on my side).

Expected behaviour should be that `cocoapods-stats` should abort uploading any statistics rather than crashing (perhaps log out the error).

**Comment by segiddins** [comment]
This ought to be fixed usin CocoaPods beta 5.
