### ISSUE TITLE
Different versions can send stats

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/cocoapods-stats#30]
If different versions of CocoaPods are installed in the same `GEM_HOME`, then this plugin can be enabled multiple times and send multiple times.

Not sure though whether we want to treat this as an issue at all, or as a more generic issue for the way CocoaPods or CLAide load plugins.

**Comment by segiddins** [comment]
This was fixed by the plugin manager in CLAide 1.0

**Comment by mrackwitz** [comment]
Okay, good to know. Just spotted it for the first time, but when running 0.39.0.
